version: 2.1 # Use version 2.1 to enable Orb usage.

orbs:
  win: circleci/windows@4.1.1 # The Windows orb gives you everything you need to start using the Windows executor.

jobs:
  build: # name of your job
    executor:
      name: win/default # executor type
      size: medium # can be medium, large, xlarge, 2xlarge

    steps:
      # Commands are run in a Windows virtual machine environment
      - checkout
      - run: 
          name: 
          command: |
            Invoke-WebRequest -Uri https://dot.net/v1/dotnet-install.ps1 -OutFile "$env:temp/dotnet-install.ps1"; powershell -executionpolicy bypass "$env:temp/dotnet-install.ps1" -Channel 6.0
      - run: Get-ChildItem -Path C:\Program Files\dotnet\sdk
      - run: Get-ChildItem -Path C:\Program Files (x86)\dotnet\sdk
      - run: Get-ChildItem -Path C:\Program Files(x86)\dotnet\sdk
      - run: dotnet build src/Auth0.OidcClient.Core/Auth0.OidcClient.Core.csproj
      - run: dotnet build src/Auth0.OidcClient.WPF/Auth0.OidcClient.WPF.csproj
      - run: dotnet build src/Auth0.OidcClient.Winforms/Auth0.OidcClient.Winforms.csproj
      - run: dotnet workload install android
      - run: dotnet build src/Auth0.OidcClient.Android/Auth0.OidcClient.Android.csproj
      - run: dotnet build src/Auth0.OidcClient.UWP/Auth0.OidcClient.UWP.csproj
